export const ProjectTable = [
  {
    isWorkingOn: false,
    asWebsite: true,
    asGithub: true,
    imageSrc: "/img/portfolio-v1.png",
    imageAlt: "Image représentant la version 1 de mon portfolio",
    Name: "Portfolio V1",
    websiteLink: "https://leo-portfolio-v1.vercel.app/",
    githubLink: "https://github.com/Leo-ThomelinTual/portfolio-app",
    Description: "La toute première version de mon portfolio.",
    dateStart: "2024",
    dateEnd: "2025",
    tags: ["TailwindCSS", "NuxtJS", "Personnel"],
  },
  {
    isWorkingOn: true,
    asWebsite: false,
    asGithub: true,
    imageSrc: "/img/MyWebGames.png",
    imageAlt: "Image représentant mon project",
    Name: "MMOType & Pong",
    websiteLink: "https://github.com/Leo-ThomelinTual/my-web-games",
    githubLink: "https://github.com/Leo-ThomelinTual/my-web-games",
    Description:
      "Ce projet regroupe un jeu de pong et un jeu où il faut taper des commandes précises pour récupérer des ressources et bien d'autres fonctionnalités à venir.",
    dateStart: "2025",
    dateEnd: "20xx",
    tags: ["TailwindCSS", "Typescript", "Symfony", "NextJS", "Personnel"],
  },
  {
    isWorkingOn: true,
    asWebsite: true,
    asGithub: true,
    imageSrc: "/img/portfolio-v2.png",
    imageAlt: "Image représentant la version 2 de mon portfolio",
    Name: "Portfolio V2",
    githubLink: "https://github.com/Leo-ThomelinTual/portfolio-app-v2",
    websiteLink: "https://leo-portfolio-v2.vercel.app/",
    Description:
      "La version 2 de mon portfolio celui où vous êtes actuellement.",
    dateStart: "2025",
    dateEnd: "2026",
    tags: ["TailwindCSS", "NextJS", "Personnel"],
  },
  {
    isWorkingOn: false,
    asWebsite: true,
    asGithub: true,
    imageSrc: "/img/spa.png",
    imageAlt: "Image d'un site SPA bien être",
    Name: "Site SPA bien être",
    githubLink: "https://github.com/Leo-ThomelinTual/spa_massage",
    websiteLink: "https://project-1-leo.vercel.app/",
    Description:
      "Un site que j'ai designer puis crée à la demande et indication d'une personne.",
    dateStart: "20/03/2026",
    dateEnd: "27/04/2026",
    tags: ["TailwindCSS", "NextJS", "Showcase"],
  },
];

export default ProjectTable;
